# Generated by Django 3.0.5 on 2020-04-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200420_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='profile_pic',
            new_name='photo',
        ),
    ]
