# Generated by Django 3.0.5 on 2020-04-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_1326'),
        ('users', '0003_auto_20200421_1246'),
    ]

    operations = [
    ]
