# Generated by Django 3.0.5 on 2020-04-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='current_money',
            field=models.IntegerField(default=0),
        ),
    ]
