# Generated by Django 3.0.5 on 2020-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200425_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pics',
            name='pic',
            field=models.ImageField(upload_to='projects/images', verbose_name='photo'),
        ),
    ]
