# Generated by Django 3.0.5 on 2020-04-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200429_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pics',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='projects.Projects'),
        ),
    ]
