# Generated by Django 3.0.5 on 2020-04-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200425_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
