# Generated by Django 3.0.5 on 2020-04-28 19:54

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200425_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pics',
            name='pic',
            field=models.ImageField(upload_to=projects.models.get_image_name, verbose_name='Project Image'),
        ),
    ]
