# Generated by Django 3.0.5 on 2020-04-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200428_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
        ),
    ]
