# Generated by Django 3.0.5 on 2020-04-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200425_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_pics',
            new_name='Picture',
        ),
    ]
