# Generated by Django 3.0.5 on 2020-04-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200429_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_tags',
            options={'verbose_name': 'Project Tag', 'verbose_name_plural': 'Project Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='project_tags',
            unique_together={('tag', 'project')},
        ),
    ]
