# Generated by Django 3.0.5 on 2020-04-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tags_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.Projects'),
        ),
    ]
