# Generated by Django 3.0.5 on 2020-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200430_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
